name: Build and Deploy

on:
  push:
    branches: main
    
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Upload jar
      uses: actions/upload-artifact@v2
      with:
        name: jar
        path: build/libs/*.jar
  
  package-docker:
    name: Build docker image
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download jar
        uses: actions/download-artifact@v2
        with:
          name: jar
          path: build/libs/
      - name: Build docker image
        uses: docker/build-push-action@v2
        with:
          push: false
